name: clang-tidy

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        # build-type: [Debug, RelWithDebInfo]
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{matrix.os}}

    steps:
      - name: Install Deps using Homebrew
        if: contains(matrix.os, 'macos')
        run: brew install bison llvm

      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: CMake
        shell: bash
        run: |
          if [[ "${{matrix.os}}" == "macos"* ]]; then
            cmake -B '${{github.workspace}}/build' -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DCMAKE_C_COMPILER=/usr/bin/clang -DBISON_EXECUTABLE=/usr/local/opt/bison/bin/bison -DLLVM_DIR="$(/usr/local/opt/llvm/bin/llvm-config --cmakedir)"
          else
            cmake -B '${{github.workspace}}/build' -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DCMAKE_C_COMPILER=/usr/bin/clang
          fi

      - name: clang-tidy
        shell: bash
        run: PATH=$PATH:/usr/local/opt/llvm/bin clang-tidy -p build $(find ./src -type f -name '*.c') --warnings-as-errors='*'
