name: Test

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        # build-type: [Debug, RelWithDebInfo]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{matrix.os}}

    steps:
      - name: clang-tidy
        run: clang-tidy --help
