name: clang-format

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{matrix.os}}

    steps:
      - name: Install Deps using Homebrew
        if: contains(matrix.os, 'macos')
        run: brew install llvm

      - uses: actions/checkout@v3

      - name: clang-format
        shell: bash
        run: clang-format --version
