name: clang-tidy

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        # build-type: [Debug, RelWithDebInfo]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{matrix.os}}

    steps:
      - name: Install Deps using Homebrew
        if: contains(matrix.os, 'macos')
        run: brew install bison llvm

      - run: |
          get-command clang
          clang --help
        if: contains(matrix.os, 'windows')
      - name: clang-tidy
        shell: bash
        run: PATH=$PATH:/usr/local/opt/llvm/bin clang-tidy --help
