name: clang-tidy

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        # build-type: [Debug, RelWithDebInfo]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{matrix.os}}

    steps:
      - name: Install Deps using Homebrew
        if: contains(matrix.os, 'macos')
        run: brew install bison llvm

      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # - run: |
      #     get-command clang
      #     clang --help
      #   if: contains(matrix.os, 'windows')

      - name: CMake
        shell: bash
        run: |
          if [[ "${{matrix.os}}" == "windows"* ]]; then
            cmake -B '${{github.workspace}}\build' -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DCMAKE_C_COMPILER='C:/Program Files/LLVM/bin/clang.exe'
          elif [[ "${{matrix.os}}" == "macos"* ]]; then
            cmake -B '${{github.workspace}}/build' -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DCMAKE_C_COMPILER=/usr/bin/clang
          else
            cmake -B '${{github.workspace}}/build' -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DCMAKE_C_COMPILER=/usr/bin/clang
          fi

      - name: clang-tidy
        shell: bash
        run: PATH=$PATH:/usr/local/opt/llvm/bin clang-tidy --help
