name: Test

on:
  push:
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        build-type: [Debug, RelWithDebInfo]
        os: [ubuntu-latest, windows-latest, macos-latest]
        asan-args: ["", "-fsanitize=address"]
      fail-fast: false
    runs-on: ${{matrix.os}}

    steps:
    - name: Install Deps using Apt
      if: contains(matrix.os, 'ubuntu')
      run: sudo apt-get install -y llvm-15-dev

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Configure CMake
      shell: bash
      run: |
          if [[ "${{matrix.os}}" == "windows"* ]]; then
            cmake -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -T ClangCL -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DCMAKE_C_FLAGS="-Wpedantic -Wall -Werror ${{matrix.asan-args}}"
          else
            cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_C_FLAGS="-Wpedantic -Wall -Werror ${{matrix.asan-args}}"
          fi

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build-type}}

    - name: Run
      shell: bash
      run: cat ${{github.workspace}}/tests/test.ptl | ${{github.workspace}}/build/ptlang

